ALTER TABLE videos ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS storage_key TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS body TEXT;

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY,
  username TEXT,
  avatar_url TEXT,
  bio TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "p_r" ON profiles FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "p_i" ON profiles FOR INSERT WITH CHECK (true);
CREATE POLICY IF NOT EXISTS "p_u" ON profiles FOR UPDATE USING (true);
